In [ ]:
import numpy as np

In [ ]:
class GridWorld:

  def __init__(self, rows, cols, start, goal):

    self.env = np.zeros((rows, cols))

    self.start = start

    self.goal = goal

    self.env[goal] = 0

    self.env[start] = 0

    # Rmat[0:n-1,1,:],Rmat[1:,3,:] = -100,-100

    # self.


    self.rows = rows

    self.cols = cols

    self.cur_values = np.zeros((rows,cols))

    


  def nextState(self, s, a):

    if a == 0:

      if s[1] == 0:
        return (s[0],s[1])

      return (s[0], s[1] - 1)

    elif a == 1:

      if s[1] == self.cols - 1:
        return (s[0], s[1])

      return (s[0], s[1] + 1)

    elif a == 2:

      if s[0] == 0:
        return (s[0], s[1])

      return (s[0] - 1, s[1])

    elif a == 3:

      if s[0] == self.rows - 1:
        return (s[0], s[1])

      return (s[0] + 1, s[1])

  def reward(self, s, a):

    if a == 0:

      if s[1] == 0:
        # return self.env[(s[0],s[1])] - 1
        return -1


      # return self.env[(s[0], s[1] - 1)]
      return -1

    elif a == 1:

      if s[1] == self.cols - 1:
        # return self.env[(s[0], s[1])] - 1
        return -1


      # return self.env[(s[0], s[1] + 1)]
      return -1

    elif a == 2:

      if s[0] == 0:
        return -1
        # return self.env[(s[0], s[1])] - 1

      # return self.env[(s[0] - 1, s[1])]
      return -1

    elif a == 3:

      if s[0] == self.rows - 1:
        # return self.env[(s[0], s[1])] - 1
        return -1


      # return self.env[(s[0] + 1, s[1])]
      return -1

    


In [ ]:
class Agent:

  def __init__(self, rows, cols, start):

    self.actions = ["left", "right", "up", "down"]

    self.policy_values = np.full((4,rows,cols),0.25)

    self.start = start

    self.cur_state = start




In [ ]:
class PolicyIteration:

  def __init__(self, agent, env):

    self.df = 1

    self.step_size = np.random.uniform(0,1)
    
    self.agent = agent

    self.env = env

  def evaluate_policy(self):

    self.env.env = self.env.cur_values.copy()

    for i in range(self.env.rows):

      for j in range(self.env.cols):

        s = (i,j)
        
        e_v = 0

        if s == self.env.goal:
          continue

        policy_a = self.agent.policy_values[:,s[0],s[1]]

        # print(policy_a)

        for a in range(len(policy_a)):

          r = self.env.reward(s,a)

          # print(r)

          s1 = self.env.nextState(s,a)

          e_v += policy_a[a] * (r + self.df * self.env.env[s1])


        # print(e_v)

        self.env.cur_values[s] = e_v

    
  def value_iteration():

    self.env.env = self.env.cur_values.copy()

    for i in range(self.env.rows):

      for j in range(self.env.cols):

        s = (i,j)
        
        e_v = []

        if s == self.env.goal or s == self.env.start:
          continue

        policy_a = self.agent.policy_values[:,s[0],s[1]]

        # print(policy_a)

        for a in range(len(policy_a)):

          r = self.env.reward(s,a)

          # print(r)

          s1 = self.env.nextState(s,a)

          e_v.append(r + self.df * self.env.env[s1])


        self.env.cur_values[s] = max(e_v)


  def findMax(self,s):

    vals = []

    if s[0] >=0 and s[1] - 1 >= 0:

      vals.append(self.env.cur_values[s[0],s[1]-1])

    else:

      vals.append(self.env.cur_values[s[0],s[1]])
      # vals.append(0)


    if s[0] >=0 and s[1] + 1 <= self.env.cols - 1:

      vals.append(self.env.cur_values[s[0],s[1]+1])

    else:

      vals.append(self.env.cur_values[s[0],s[1]])
      # vals.append(0)



    if s[0] - 1 >= 0 and s[1] >= 0:

      vals.append(self.env.cur_values[s[0] - 1,s[1]])

    else:

      vals.append(self.env.cur_values[s[0],s[1]])
      # vals.append(0)



    if s[0] + 1 <= self.env.rows - 1 and s[1] >= 0:

      vals.append(self.env.cur_values[s[0] + 1,s[1]])

    else:

      vals.append(self.env.cur_values[s[0],s[1]])
      # vals.append(0)

    return vals


  def improve_policy(self):

    for i in range(self.env.rows):

      for j in range(self.env.cols):

        s = (i,j)

        values = self.findMax(s)

        c = np.argmax(values)

        p = [0,0,0,0]

        p[c] = 1

        self.agent.policy_values[:,s[0],s[1]] = p


  def printPolicy(self):

    grid = np.zeros((self.env.rows,self.env.cols))    

    for i in range(self.env.rows):

      for j in range(self.env.cols):

        s = (i,j)

        grid[s] = np.argmax(self.agent.policy_values[:,s[0],s[1]])


    print(grid)

            



In [ ]:
e = GridWorld(4,4,(0,0),(3,3))

In [ ]:
ag = Agent(4,4,(0,0))

In [ ]:
p = PolicyIteration(ag, e)

In [ ]:
for i in range(10):

  p.evaluate_policy()
  p.improve_policy()
  print(p.env.env)
  print("end")
  # break

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
end
[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
end
[[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]
end
[[-3. -3. -3. -3.]
 [-3. -3. -3. -2.]
 [-3. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end
[[-4. -4. -4. -3.]
 [-4. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end
[[-5. -5. -4. -3.]
 [-5. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end
[[-6. -5. -4. -3.]
 [-5. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end
[[-6. -5. -4. -3.]
 [-5. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end
[[-6. -5. -4. -3.]
 [-5. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end
[[-6. -5. -4. -3.]
 [-5. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
end


In [ ]:
p.env.env

array([[-6., -5., -4., -3.],
       [-5., -4., -3., -2.],
       [-4., -3., -2., -1.],
       [-3., -2., -1.,  0.]])

In [ ]:
p.printPolicy()

[[1. 1. 1. 3.]
 [1. 1. 1. 3.]
 [1. 1. 1. 3.]
 [1. 1. 1. 1.]]


In [ ]:
p.agent.policy_values

array([[[0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25]]])